### ISSUE TITLE
Querying uMp axis angle

### ISSUE THREAD

**Issue by obria006** [sensapex/sensapex-py#11]
Hi, I'm trying to query the uMp d-axis angle using the SDK v1.022. I have code that I wrote previously that worked with SDK v0.833, but my new code returns an error that I'm uncertain of how to trouble shoot.

Can anyone provide guidance on successfully querying the axis angle in SDK v1.022? I'm using Python 3.7.5 on Windows 10.

```
#Works using SDK 0.833.
from sensapex import UMP
u = UMP.get_ump()
# Returns d-axis angle in degrees *10
ang = u.call("ump_cmd_get_axis_angle",c_int(1),c_int(3),c_int(1))
print(f'Angle: {ang}')

>>> Angle:  271
```

```
#Fails using SDK 1.022
from sensapex import UMP
ang = u.call("ump_get_axis_angle",c_int(1))
print(f'Angle: {ang}')

>>> Traceback (most recent call last):
  File "c:/VirEnvs/RobotagSeq375_DEV/RobotagSeq/Modules/Sensapex/sensapex_utils.py", line 66, in <module>
    ang = u.call("ump_get_axis_angle",c_int(1))
  File "C:\VirEnvs\RobotagSeq375_DEV\lib\site-packages\sensapex\sensapex.py", line 533, in call
    rval = getattr(self.lib, fn)(self.h, *args)
OSError: exception: access violation writing 0x0000000000000066
```

**Comment by outofculture** [comment]
Yeah, you'll need to supply a third argument, of type `byref(c_float())`, for the angle to be saved into. See, e.g. `sensapex.sensapex.UMP.get_pressure`.
