### ISSUE TITLE
Unable to use SDK in Linux

### ISSUE THREAD

**Issue by kjy5** [sensapex/sensapex-py#17]
I downloaded the SDK from here http://dist.sensapex.com/misc/um-sdk/latest/umsdk-1_022-src.zip, unzipped and copied `libum.so` into my project files. I then used `UMP.set_library_path` to point to the directory I placed `libum.so` in. However, when I run `UMP.get_ump()` I get the following error:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/sensapex/sensapex.py", line 359, in get_ump
    cls._single = UMP(address=address, group=group, start_poller=start_poller)
  File "/usr/local/lib/python3.10/site-packages/sensapex/sensapex.py", line 375, in __init__
    self.lib = self.get_lib()
  File "/usr/local/lib/python3.10/site-packages/sensapex/sensapex.py", line 323, in get_lib
    cls._lib = cls.load_lib()
  File "/usr/local/lib/python3.10/site-packages/sensapex/sensapex.py", line 339, in load_lib
    return ctypes.cdll.LoadLibrary(os.path.join(cls._lib_path, "libum.so"))
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /path/to/project/libum.so: cannot open shared object file: No such file or directory
```

I'm running this in docker with the [`python:latest`](https://hub.docker.com/layers/python/library/python/latest/images/sha256-607635763e54907fd75397fedfeb83890e62a0f9b54a1d99d27d748c5d269be4?context=explore) image. How can I get the SDK to work on linux?

Thanks!

**Comment by outofculture** [comment]
Just to be clear, is the `libum.so` file in the `/path/to/project/` directory? What is the output of `docker exec CONTAINER ls /path/to/project`? That seems more like filler text that got copied into place than the actual location of a file. See if you can get the following code to not error:

```python
import ctypes
ctypes.cdll.LoadLibrary("/some/path/you/think/correctly/specifies/the/in-docker/location/of/libum.so")
```

And that should give you the parent directory to use in `UMP.set_library_path`.

**Comment by kjy5** [comment]
Thanks for the quick reply! Yes, sorry, to clarify `/path/to/project/` is a fake path I made up to represent the real path, but the true path is real.

The result of running `docker exec CONTAINER ls /path/to/project` does yield `libum.so`. I also have `libum.dll` in that directory as well (the `dll` works fine on windows).

Running the `ctypes.cdll.LoadLibrary` still results in the same error
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /path/to/project/libum.so: cannot open shared object file: No such file or directory
```

**Comment by outofculture** [comment]
Huh. Well, in that case, something else we're assuming about the environment must not be true. I would try putting the libum.so file in different places, or just trying to access the directories at all from inside python, e.g. `os.path.exists('/path')`, to suss out what the actual environment is.

**Comment by kjy5** [comment]
`os.path.exists` still returns true. Is it possible that the `libum.so` files I found in the zip are not valid? Should I be recompiling them or using alternate files like `libum.so.1`?

**Comment by outofculture** [comment]
Hopefully not. Invalid formats should give errors more like: `OSError: /path/to/project/libum.so: invalid ELF header`. Getting `No such file or directory` usually means python just can't find it. Does `open("/path/to/project/libum.so")` work?

**Comment by kjy5** [comment]
`open` does work

**Comment by kjy5** [comment]
Ok I ended up recompiling and found out what happened. Compilation creates `libum.so.1.0.0` which is then symbolically linked into `libum.so`. This linking was why docker (or any system for that matter) couldn't find the file since it was a symbolic link to a non-existent file (wherever the SDK was compiled). By renaming `libum.so.1.0.0` to `libum.so` and copying that file into the project, the SDK was found.

Thanks for your help today!
