### ISSUE TITLE
Restore factory Settings

### ISSUE THREAD

**Issue by usernamezhuzhu** [sensapex/sensapex-py#4]
Can the micromanipulator be restored to factory Settings? What are the risks

![picture](https://user-images.githubusercontent.com/59303910/119849353-220c2c00-bf3f-11eb-9f8f-ae66a5a09e97.jpg)

**Comment by outofculture** [comment]
At a minimum, you will have to re-configure the TSC's "group" to match the rest of your Sensapex hardware. Any other configuration options you had customized will be reset. It will also reboot the TSC, during which it will be unresponsive.
