### ISSUE TITLE
 微操纵器并行控制 Parallel control of micromanipulator

### ISSUE THREAD

**Issue by usernamezhuzhu** [sensapex/sensapex-py#5]
![image](https://user-images.githubusercontent.com/59303910/119868194-54268980-bf51-11eb-8da0-c834f3c238a1.png)
Good moring, why do the two manipulators not run synchronously after running the above code, and the delay is very large，Can you tell me how to make two micro manipulators move in parallel, thank you。

**Comment by outofculture** [comment]
Hello!

I think they should use they same handle. Does that help?

 - Martin

**Comment by usernamezhuzhu** [comment]
![image](https://user-images.githubusercontent.com/59303910/119919449-0df71780-bf9d-11eb-82fa-b774602d36b3.png)

I tried, but there is still delay. Can you give me an example of parallel control? thank you

**Comment by outofculture** [comment]
I can't offer much of a minimal example, but [here's a section in ACQ4](https://github.com/acq4/acq4/blob/python3/acq4/modules/MultiPatch/multipatch.py#L291) that controls multiple manipulators to position themselves.

Another note: you're posting issues on the _python_ bindings for Sensapex hardware. I expect you actually want to post your questions to https://github.com/sensapex/umsdk
