### ISSUE TITLE
Can't find the (older ?) umsdk libraries corresponding to current sensapex-py package

### ISSUE THREAD

**Issue by DayanZc** [sensapex/sensapex-py#6]
ump = UMP.get_ump()
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-5-401c00a120a5> in <module>
----> 1 ump = UMP.get_ump()

After going through the different v1 umsdk libraries, I am still getting the following error 

AssertionError: SDK version v0.920 or lower required (your version is b'v1.001')

Although, I could not find the lower versions of umsdk (which seem to be split in the different ump-sdk and smx-sdk libraries ?)
Is this not yet supported or am I missing something ?

Thanks

**Comment by outofculture** [comment]
Oh dear, it seems they stopped distributing the old ones. Yeah, that's a problem. You can grab the source code for [umsdk](https://github.com/sensapex/umsdk) and roll back to 9fd5cb6dda277de76355a40168cdc9b62160c946 and then build the file that way. Updating this wrapper to 1.010 would also be pretty easy; I'll try to get that done this week.

**Comment by DayanZc** [comment]
Ok so at least I caught this. Great if you manage to update the wrapper, I'm totally fine waiting for a few weeks, and I'm not comfortable enough with C libraries to easily build the file from earlier version of umsdk (especially on Windows, though it would be a good training).
Thanks !

**Comment by outofculture** [comment]
Okay, I have versions on pypi that are compatible with 1.001 through 1.011 (use v1.011.0) and 1.021 (v1.021.0 on pypi).
