### ISSUE TITLE
Add fault inspection tools

### ISSUE THREAD

**Issue by campagnola** [sensapex/sensapex-py#7]
Need some way to diagnose faults and send reports. These might include:

- pcap logging
- network interface configuration
- ping to all known devices
- user feedback (when? red lights? context?)
- on-device crash logs
- sdk/firmware version numbers

This might require a ui that persists across device reboots (including sensapex or the PC) until crash logs can be retrieved.

**Comment by outofculture** [comment]
The [pcap branch](https://github.com/sensapex/sensapex-py/tree/pcap) attempts to add the first part of this.

As a library, we don't really have the ability to decide how to interact with the user when errors happen, but we can offer the ability to add custom fields to the crash log, and encourage their use with an example program.
